### ISSUE TITLE
Architecture layout doesn't show certain structures

### ISSUE THREAD

**Issue by finger563** [deepforge-dev/deepforge#1143]
e.g.:

![image](https://user-images.githubusercontent.com/213467/43482177-96cd5572-94cd-11e8-9021-2f5e37dceb3f.png)

In this case `Conv2D` goes into both `Conv2DTranspose` and `Concatenate`, and `Conv2DTranspose` also goes into concatenate

**Comment by finger563** [comment]
this also makes selecting the connections / changing the inputs impossible

**Comment by finger563** [comment]
More complex example - where it tries to work properly in some cases:

![image](https://user-images.githubusercontent.com/213467/43485400-bcc723ee-94d6-11e8-8486-ca4744a15708.png)

**Comment by brollb** [comment]
Moved to https://github.com/deepforge-dev/deepforge-keras/issues/109
