### ISSUE TITLE
Add matplotlib image support

### ISSUE THREAD

**Issue by brollb** [deepforge-dev/deepforge#1218]
Currently, deepforge supports using `matplotlib` for generating 2D plots. It would be great if this could be extended to support displaying images as well (particularly useful for image classification problems!).

**Comment by brollb** [comment]
Job feedback is currently encoded in the stdout for a job, decoded by the server, and then the project is updated to contain the actual corresponding objects. As matplotlib supports custom backends, we have a custom backend defined for use within deepforge which [prints a JSON representation of the graph when using it for plotting](https://github.com/deepforge-dev/deepforge/blob/master/src/plugins/GenerateJob/templates/backend_deepforge.py#L249).

To add support for images, we would need to:
- save the image to the filesystem (add to the [custom matplotlib backend](https://github.com/deepforge-dev/deepforge/blob/master/src/plugins/GenerateJob/templates/backend_deepforge.py))
- upload the image to the deepforge server (using the blob client and retrieving the hash)
    - This should already be done [here](https://github.com/deepforge-dev/deepforge/blob/master/src/plugins/GenerateJob/templates/start.ejs#L88-L114) as long as the matplotlib backend saves the image to `metadata/` as a png and then prints the cmd to stdout.
    - An example can be found in deepforge v1 where this was performed by a `deepforge` global in lua: https://github.com/deepforge-dev/deepforge/blob/v1.x/src/plugins/GenerateJob/templates/deepforge.ejs#L80-L81
- encode an image update message in the stdout which passes the image info and the hash
    - This should already be handled by the link from the previous point
- ensure that the image update message is [decoded properly by deepforge](https://github.com/deepforge-dev/deepforge/blob/master/src/plugins/ExecuteJob/ExecuteJob.Metadata.js#L92-L126) and the corresponding image node is created.
    - This should work out of the box but there may have been changes since v1 that may require some modifications (namely [here](https://github.com/deepforge-dev/deepforge/blob/master/src/plugins/ExecuteJob/ExecuteJob.Metadata.js#L108-L126))

**Comment by umesh-timalsina** [comment]
Now that #1329 is merged, Incremental support to `Image` trace with updated meta-model can be provided.

**Comment by umesh-timalsina** [comment]
Steps for Image Support is quite different for `plotly` than https://github.com/deepforge-dev/deepforge/issues/1218#issuecomment-476719938.
1. [Custom Matplotlib Backend](https://github.com/deepforge-dev/deepforge/blob/master/src/plugins/GenerateJob/templates/backend_deepforge.py) Should be updated to get Image Information(The best strategy now is the JSON Dump a numpy Matrix although this could be changed to support any other form of encoding).
2. Update The MetaModel such that node `Image` is contained within the `SubGraph`. 
3. So, the image information will now be available upon plots creation.
4. Update the [`ExecuteJob.Metadata.js`](https://github.com/deepforge-dev/deepforge/blob/master/src/plugins/ExecuteJob/ExecuteJob.Metadata.js) to create `Image` Nodes upon getting the information.
5. Update [`PlotlyDescExtractor.js`](https://github.com/deepforge-dev/deepforge/blob/master/src/common/viz/PlotlyDescExtractor.js) to get the plotly JSON from the image Node.
6. Update [`ExecutionIndexControl.js`](https://github.com/deepforge-dev/deepforge/blob/master/src/visualizers/panels/ExecutionIndex/ExecutionIndexControl.js) to send updates regarding Images to the Widget.
