### ISSUE TITLE
Use Miniconda to Manage Dependencies

### ISSUE THREAD

**Issue by umesh-timalsina** [deepforge-dev/deepforge#1402]
To Solve #1392 as well as enable public deployment, deepforge's python dependencies should be managed by using miniconda.

**Comment by umesh-timalsina** [comment]
1. Add a shell script to install conda (on post install) and create a conda-environment for deepforge
2. The start script should be preceeded by conda activate to make sure deepforge runs in a proper environment.
3. Install conda on worker machine => check environements => Create deepforge environemtn

**Comment by brollb** [comment]
I don't think we should install conda for users as this is a relatively easy task for users but would be annoying to maintain for all the different platforms that people want to use. 

A similar argument could be made for starting deepforge in a conda environment but that should be relatively easy programmatically (without the platform issues of the earlier issue) so it probably isn't a big deal.

**Comment by umesh-timalsina** [comment]
See #1392, #1474, #1447.
