### ISSUE TITLE
Docker Image For SciServer Compute

### ISSUE THREAD

**Issue by umesh-timalsina** [deepforge-dev/deepforge#1427]
Currently, SciServer Jobs run in `Python + R` docker image. Sciserver has a new Image called `SciServer Essentials`. It has `tensorflow, pytorch` already installed. So, it would be nice to run the pipelines in that image or provide option like the Jobs Domain.

**Comment by brollb** [comment]
Yeah, this sounds great!

**Comment by brollb** [comment]
One thing worth noting is that the "SciServer Essentials" image is using tensorflow v2. We should do some additional testing to ensure that we are compatible with this change.

**Comment by brollb** [comment]
This has been updated in https://github.com/deepforge-dev/deepforge/pull/1568. The tensorflow issue is a non-issue as we are using custom conda environments
