### ISSUE TITLE
Bad formatting for subfigure titles

### ISSUE THREAD

**Issue by brollb** [deepforge-dev/deepforge#1450]
When creating multiple subfigures (with titles), the title can overlap the label for the x-axis as shown below:

![DeepinScreenshot_select-area_20200304111221](https://user-images.githubusercontent.com/4982789/75904623-282d5e80-5e09-11ea-9dbc-a68aa8cbebf5.png)

**Comment by brollb** [comment]
Upon closer inspection, it also appears that the titles are not placed in the same position above each subfigure. In the left column, the titles are further to the right than in the right column...

**Comment by umesh-timalsina** [comment]
This could be resolved by using the property `domain` of the plotlyjs x and y axis. Though, https://github.com/plotly/plotly.js/issues/2746 has a pretty solid discussion on why this will be a challenge to generate a dynamic subplot title without bad formats. A thorough look should be given to plotly.py and how it implements subplots title.

**Comment by umesh-timalsina** [comment]
I think we are better off by adding plot number (a.), (b.), (c.)... and adding a text area at the end with all the subplots title.
