### ISSUE TITLE
Cannot read property 'title' of undefined (PlotlyDescExtractor)

### ISSUE THREAD

**Issue by brollb** [deepforge-dev/deepforge#1462]
There is currently an error thrown by the plot visualizer that occurs when restarting an individual job:
![DeepinScreenshot_select-area_20200305091212](https://user-images.githubusercontent.com/4982789/75995147-9df50100-5ec1-11ea-9eb2-0b1668054ea2.png)

Even if there is something happening incorrectly in the restart logic, this should fail gracefully and not throw an exception...

**Comment by umesh-timalsina** [comment]
For this to work correctly, the else block should only be executed if and only if `desc` has a `subPlot`.
