### ISSUE TITLE
3D Scatter support in matplotlib

### ISSUE THREAD

**Issue by brollb** [deepforge-dev/deepforge#1463]
It would be great to add support for 3D scatter plots for exploring datasets. Plotlyjs [already supports this](https://plot.ly/javascript/3d-scatter-plots/) so it is simply a matter of:
- including it in the JSON representation created from the custom matplotlib backend
- updating the metamodel
- converting the metamodel data into plotly JSON

Here is a simple example visualizing embeddings of the galaxy images from the [redshift example](https://github.com/deepforge-dev/examples/tree/master/redshift) color-coded by their redshift value (darker is a larger redshift value):
![DeepinScreenshot_select-area_20200305150743](https://user-images.githubusercontent.com/4982789/76025715-1fb15280-5ef3-11ea-83ac-9d333317336b.png)

**Comment by umesh-timalsina** [comment]
A library like [mplexporter](https://github.com/mpld3/mplexporter) could be immensely helpful in data-extraction from matplotlib figures.

**Comment by umesh-timalsina** [comment]
3D scatter plots are represented as [`Patch3DCollection`](https://matplotlib.org/mpl_toolkits/mplot3d/api.html#mpl_toolkits.mplot3d.art3d.Patch3DCollection) in [matplotlib](https://matplotlib.org/mpl_toolkits/mplot3d/tutorial.html#scatter-plots).

**Comment by umesh-timalsina** [comment]
Depends on #1552/#1553.
