### ISSUE TITLE
Start deepforge-worker in a conda environment

### ISSUE THREAD

**Issue by umesh-timalsina** [deepforge-dev/deepforge#1474]
Related to #1402, #1466. The worker dependencies need to be updated on starting a deepforge-worker.

**Comment by brollb** [comment]
This one is a little tricky because it might be nice to move the worker logic to its own repo so users don't need to install all of deepforge on each worker machine. This does make installing dependencies dictated by deepforge extensions a little trickier though.

**Comment by brollb** [comment]
Closing in favor of #1528
