### ISSUE TITLE
Starting deepforge from a non-base conda environment fails in Linux

### ISSUE THREAD

**Issue by umesh-timalsina** [deepforge-dev/deepforge#1494]
This is caused because `source` doesn't find activate command outside of `base`.

```
MongoDB is already running!
/bin/bash: activate: No such file or directory
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! deepforge@2.1.1 start: `node ./bin/deepforge start`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the deepforge@2.1.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/catfished/.npm/_logs/2020-03-12T21_03_55_253Z-debug.log

```

The correct way to start deepforge at this point is(/bin/bash):
1. `conda init`(if not arleady done)
2.  `conda activate base`
3. `./bin/deepforge start`

**Comment by umesh-timalsina** [comment]
This happens because `${ANACONDA_INSTALL_DIR}/bin` is removed from ${PATH}, whenever you activate a conda environment. So, it should be appended to the path before starting deepforge.

**Comment by brollb** [comment]
It's not clear if this is an issue that deepforge should try to solve. If conda is not installed or initialized, why should deepforge try to fix these issues for the user? 

If this is a feature that we try to manage with deepforge then it is our responsibility to support this across platforms, etc. As this feature doesn't really seem to be helping the user out with much, I am not convinced that it is worth it. I would opt for printing a warning if there is an error with conda when switching to the deepforge conda environment and then just making sure this is documented.

**Comment by umesh-timalsina** [comment]
As this would require hairy path variables manipulations. Should be documented and user warning should be issued instead.

**Comment by brollb** [comment]
@umesh-timalsina This is no longer an issue, correct?
