### ISSUE TITLE
Add a release docker action

### ISSUE THREAD

**Issue by umesh-timalsina** [deepforge-dev/deepforge#1516]
Similar to what we have for latest tags, we should have a workflow on release, which builds the docker images and pushes to docker hub and hopefully deploy `deepforge/server:stable` at `editor.deepforge.org`.

**Comment by brollb** [comment]
It might be nice to split this into two issues:
- build & push the docker image on releases (this issue)
- update editor.deepforge.org (another issue)

**Comment by umesh-timalsina** [comment]
Here's a release plan:
1. An workflow that runs test, followed by a `docker build` and `publish` to docker hub, followed by `npm publish` with a dry run, followed by `npm publish`. Followed by a ssh-deploy to `editor.deepforge.org`
