### ISSUE TITLE
Update Documentation to the new API

### ISSUE THREAD

**Issue by umesh-timalsina** [deepforge-dev/deepforge#1517]
We should update the `deepforge` documentation to the newer API. Have sections on storage and compute adapaters, docker files among others.

**Comment by brollb** [comment]
After taking a look at the current docs, here are some big places that need some updating:
- [ ] Operation feedback
- [ ] Getting started. This was written for a user looking to spin up their own deployment so this will need to be moved and should contain info about connecting their own compute, storage and maybe a hello world sort of example.
- [ ] Add a walkthrough of the redshift example?
- [ ] Add an "Integration" section.
- [ ] Update the CLI documentation
- [ ] Deployment documentation needs to be updated in light of compute adapters, etc.
- [ ] Custom operations. This needs to be updated to include information about dependencies. Screenshots also need to be updated.

@umesh-timalsina - Do you mind taking "Operation Feedback", the "Integration" section (I believe you have already worked on that some), and a walkthrough of the redshift example.

I can get started on "Getting started", "Deployment", "Custom Operations", and the CLI docs.

**Comment by umesh-timalsina** [comment]
Sure.
