### ISSUE TITLE
Flaky integration tests in CI

### ISSUE THREAD

**Issue by brollb** [deepforge-dev/deepforge#1540]
![DeepinScreenshot_select-area_20200319144936](https://user-images.githubusercontent.com/4982789/77108886-fd3e2f80-69f0-11ea-9078-f06585486e8a.png)

**Comment by brollb** [comment]
I suspect this could be related to the tests being run in parallel but using a shared resource (SciServer Files).

**Comment by umesh-timalsina** [comment]
We should add a `cron` Job in travis to test this is actually the case
