### ISSUE TITLE
Parse Legends For a Matplotlib Figure

### ISSUE THREAD

**Issue by umesh-timalsina** [deepforge-dev/deepforge#1551]
Currently, the legends for a figure are parsed from labels (for line plots). Alternatively, we could parse legend for the `axes` from `matplotlib` and assign the labels.

**Comment by brollb** [comment]
What's the motivation for changing this? Is there an issue with the current approach?

**Comment by umesh-timalsina** [comment]
This is to replicate user program. Don't show the legend if the legend visibility is off in Matplotlib.

**Comment by umesh-timalsina** [comment]
This will be closed by #1747.
