### ISSUE TITLE
Issues with worker environment in #1586

### ISSUE THREAD

**Issue by umesh-timalsina** [deepforge-dev/deepforge#1587]
Darn. I didn't look at this closely enough and there are a few issues:
- if conda isn't used, this will just error
- if the job has dependencies, the incorrect environment will be used

_Originally posted by @brollb in https://github.com/deepforge-dev/deepforge/pull/1586#issuecomment-608515754_

**Comment by brollb** [comment]
Actually, it looks like the `envName` will be passed in if there are job dependencies so only the second comment is an issue.
