### ISSUE TITLE
Extend ImportArtifacts to be able to "import" artifacts where the data already exists in the given storage backend.

### ISSUE THREAD

**Issue by umesh-timalsina** [deepforge-dev/deepforge#1608]
It would be nice if we are able to `symlink` paths from all the storage backends. Currently, we are just able to upload data from local storage file system.

**Comment by brollb** [comment]
By "symlink paths from all storage backends", you mean that we should be able to "import" artifacts where the data already exists in the given storage backend, right?

**Comment by umesh-timalsina** [comment]
Yeah. It might be helpful to bring data availability to upper lever operation interface. This can be done at the operation (Python script), but since we already can gather metadata on an artifact stored in a `Storage Backend`, it might be nicer to bring this capability to the user.
