### ISSUE TITLE
Use username from sciserver-storage config for url formation

### ISSUE THREAD

**Issue by umesh-timalsina** [deepforge-dev/deepforge#1634]
Currently, in `sciserver-storage` config, we already take in the username. It might be nicer to exclude this from volume name.

**Comment by brollb** [comment]
This would not work for shared volumes. In other words, the username only is the prefix to the volume when I am working on my own personal drive. Otherwise, it could have other values.

**Comment by umesh-timalsina** [comment]
This is closed because it is not possible to track various shared volumes without providing username in the volume
