### ISSUE TITLE
npm start fails if conda not available

### ISSUE THREAD

**Issue by brollb** [deepforge-dev/deepforge#1678]
Although it is preferred to use conda, it would be good to be able to run deepforge without it. Of course, dependencies would need to be already installed and would not be able to be automatically installed. Currently, running `npm start` results in the following error:
![DeepinScreenshot_select-area_20200504100257](https://user-images.githubusercontent.com/4982789/80980708-9634d880-8dee-11ea-9c76-0b0a733b436b.png)

**Comment by brollb** [comment]
I guess this actually is the same as auto-detecting conda support (since we already have support for the `-N` flag.

**Comment by umesh-timalsina** [comment]
Doesn't https://github.com/deepforge-dev/deepforge/blob/7b58882eec8abb1312be3ca3ce6747d85093c703/package.json#L16 already handle it.

**Comment by brollb** [comment]
That's why I added the comment about auto-detecting conda support. :) Basically, it can be a little annoying that `npm start` fails when conda is not available. It would be nice to either detect this and print a meaningful error message or print a warning and run without conda support.

**Comment by brollb** [comment]
This specific error is caused by `activate` not being found in the `PATH`. In my case, adding `~/anaconda/bin/` to my `PATH` fixed it:

```bash
export PATH=$PATH:$HOME/anaconda3/bin
```
