### ISSUE TITLE
Add option to load artifact without deserialization

### ISSUE THREAD

**Issue by umesh-timalsina** [deepforge-dev/deepforge#1679]
It might be helpful to have an option to load an artifact in binary mode without deserializing it. Because most python packages might have their own way of handling data and if we just provide the raw binary the logic to process it could be handled in the operation itself.

**Comment by brollb** [comment]
this shouldn't be very hard to do currently using custom serializers like in https://github.com/deepforge-dev/deepforge/issues/1219
