### ISSUE TITLE
Store PlotlyJSON directly in the project model?

### ISSUE THREAD

**Issue by brollb** [deepforge-dev/deepforge#1745]
Working on the interactive tensor plotting capabilities has brought some issues to light with the current approach taken with plots. The tensor plotting capabilities include plotting one-dimensional tensors as shown below.

![DeepinScreenshot_20200703093236](https://user-images.githubusercontent.com/4982789/86602788-cb81b200-bf68-11ea-87d4-45271b176423.png)

However, this can not be represented in the current metamodel nor the matplotlib backend (required for reproducing the plot). The main issue here is not just that it isn't supported but that adding support requires changes to the [metamodel](https://github.com/deepforge-dev/deepforge/blob/master/src/seeds/pipeline/pipeline.webgmex) and the [matplotlib backend](https://github.com/deepforge-dev/deepforge/blob/master/src/plugins/GenerateJob/templates/backend_deepforge.py#L367-L432) (which is already somewhat large).

Alternatively, we could simply store the plotly JSON directly in our metamodel. This should greatly simplify the matplotlib backend code as it can just use `plotly.tool.mpl_to_plotly` and would provide support for almost all plots immediately - rather than adding custom code for each one (where it feels like we have begun to reinvent the wheel).

**Comment by brollb** [comment]
One remaining challenge would be to add support for click/selection events: https://plotly.com/javascript/plotlyjs-events/

This isn't any harder using this approach but it is something that has not been covered here.

**Comment by umesh-timalsina** [comment]
There will be following questions:

1. The current `metamodel` for storing figure info is as shown below:
![image](https://user-images.githubusercontent.com/11476842/86606945-44373d00-bf6e-11ea-9d4c-b7f19dcaabc4.png)
What will be the approach to store a `PlotlyJSON` into a metamodel?

2. Should we distinguish subplots and plots `metanodes`?

**Comment by brollb** [comment]
Since the plotly JSON, has all this info, we might be able to just update the `Graph` node to have a `data` field with the plotly JSON.

**Comment by brollb** [comment]
As far as the second question, ideally we would be able to contain all the info in the single node and allow plotly JSON to contain the subfigure info.

**Comment by umesh-timalsina** [comment]
There are couple of challenges with the current approach:

1. Exporting Images with `mpl_to_plotly` is not yet supported:
```
Aw. Snap! You're gonna have to hold off on the selfies for now. Plotly can't import images from matplotlib yet!
```
2. Exporting 3D plots with `mpl_to_plotly` is not yet supported.
