### ISSUE TITLE
Add plotly to sciserver compute image (prepare script)

### ISSUE THREAD

**Issue by brollb** [deepforge-dev/deepforge#1826]
We need to add plotly to the deepforge image on sciserver. In the meantime, we should install it in the preparation script.

**Comment by umesh-timalsina** [comment]
The other issue is since we are pinning `matplotlib` version to `3.2.2` in the image?

**Comment by brollb** [comment]
good question. I think it should be good this time but might be good to test just to make sure. The [dockerfile](https://github.com/deepforge-dev/deepforge/blob/master/docker/Dockerfile.workerenv) uses the exported worker environment file created from `deepforge create-env`.
