### ISSUE TITLE
Provide Job Name in submitterDID submitting a Job to sciserver compute??

### ISSUE THREAD

**Issue by umesh-timalsina** [deepforge-dev/deepforge#1830]
It might be nice to submit a Job in `sciserver-compute` with its name, it will be easier to debug in dashboard when executing  a `pipeline` with multiple jobs. However, there's no clear advantage other than that. 

![image](https://user-images.githubusercontent.com/11476842/89326192-89bf5680-d64f-11ea-983e-6f2840aaa917.png)

**Comment by brollb** [comment]
This is a good idea but will require a little thought about what sort of additional metadata will be useful for job creation. (It would be good to update the compute client interface for `createJob` to not only accept the hash but also a `metadata` argument.) Compute adapters may be used for other tasks, such as interactive compute sessions, so it might be good to think a bit about what sort of additional, generic metadata might be useful to the variety of compute adapters.

Maybe "name" is the only thing we care about but it's possible that other info could be of interest in the future. If there is additional info in the future, it might be good to simply create a `metadata` argument that can have a lot of optional values (maybe start time?). If we are confident there are not many other types of info that would be added, we could simply add a `name` argument...

Anyway, the short answer is that this is a good idea but requires modification of the compute adapter interface. Although it is only a minor change, it would be nice to think about it carefully before adding it to prevent an annoying or confusing interface in the future.

**Comment by brollb** [comment]
It might be nice to revamp the JobOriginsAPI in favor of a richer compute API as the JobOriginsAPI is tied to the GME executor framework.

One tricky thing is that interactive compute will not have an associated job, pipeline, etc. Maybe we should have them as optional? Something like the following for interactive compute sessions:
```
{
  name: 'Train Neural Network',
}
```
or
```
{
  job: 'Train',
  pipeline: 'cifar10',
  branch: 'master',
}
```

The WebGME Executor Framework compute client would need to record the latter metadata info in the database for use with the compute dashboard (or it could simply be changed to show a name like SciServer compute's dashboard).
