### ISSUE TITLE
Pipeline not starting on SciServer Compute

### ISSUE THREAD

**Issue by brollb** [deepforge-dev/deepforge#1849]
It appears that for some users (such as kmoore), running a pipeline on SciServer Compute hangs indefinitely. Looking at the server logs shows:
```
2020-08-06T16:59:31.823Z - error: [gme:server:worker:simpleworker:pid_514591:WorkerFunctions:PluginManagerBase:plugin:ExecutePipeline] Could not execute "GetCifar10Data": Error: SciServer Files request failed: Error in job definition
```

As this appears to be specific to this user, I suspect the error is happening on the SciServer side. However, this should be handled better by deepforge so we don't need to go to the server logs.

**Comment by umesh-timalsina** [comment]
The issue seems to be that the sciserver docker image `DeepForge` is accessible to some users while not for other users. So, I would recharacterize this issue not to be a code related bug in deepforge but rather an issue with sciserver's docker image for `deepforge` access to every account.

**Comment by brollb** [comment]
Thanks, @umesh-timalsina for finding the source of the issue. I am going to leave this issue since the error is not handled properly in deepforge. (The pipeline should show the error when an error occurs during job creation.)
