### ISSUE TITLE
Show all pipeline figures from execution index

### ISSUE THREAD

**Issue by brollb** [deepforge-dev/deepforge#1907]
Since we aren't combining plots anymore from the execution index, it might be nice to show all figures from the selected executions.

**Comment by umesh-timalsina** [comment]
Don't we already do that? I.e. use the widget to show multiple plotly plots.

**Comment by brollb** [comment]
I thought so but is that the case when there are multiple plots generated by a single execution? I was reviewing #1896 and @KyleAMoore mentioned that only one plot per execution is shown.

**Comment by brollb** [comment]
Then we can remove things like "Unfortunately, only one of the two figures can be viewed from this page. " from the docs :)

**Comment by KyleAMoore** [comment]
Unless I am missing something, it is correct that pipeline executions which generate multiple figures will only display one of those figures. See the screenshot linked for example. The selected execution generates two plots, one from each of the last two operations. Only one is being displayed, and I cannot find a control that will switch between the two plots or shows them together.

As far as I can tell, the only way right now to view the second plot that is generated is to open the console output for the unshown figure and select the graph view. In #1896, I use this as an opportunity to introduce this feature, so it is convenient for documentation purposes, but it may be preferable to allow switching from the executions tab for user friendliness.

![image](https://user-images.githubusercontent.com/28512577/93392311-320f3000-f836-11ea-9010-0692375e1f0b.png)

**Comment by umesh-timalsina** [comment]
@KyleAMoore, you are right only one figure is grabbed for an execution currently, we can support this feature, but not sure if we wanted to use something like https://github.com/deepforge-dev/deepforge/issues/1766#issuecomment-659700506 or extend the existing visualizer.
