### ISSUE TITLE
GitHub Actions: Deprecating set-env and add-path commands

### ISSUE THREAD

**Issue by umesh-timalsina** [deepforge-dev/deepforge#1983]
https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/

This is causing problems with our deployment scripts. This should be updated in our workflow.

**Comment by brollb** [comment]
I already updated this in netsblox. It might be a useful example.

**Comment by brollb** [comment]
https://github.com/NetsBlox/NetsBlox/commit/eafdeebb9fd82d8f2c4c0f3c1d56f29791fe936e
