### ISSUE TITLE
Creating disconnected execution from pipeline

### ISSUE THREAD

**Issue by brollb** [deepforge-dev/deepforge#2000]
I am not sure of the root cause but it seems this pipeline:
![DeepinScreenshot_select-area_20210311121924](https://user-images.githubusercontent.com/4982789/110835039-e4fb9c00-8263-11eb-8cb6-1b203c0d44f4.png)

is producing this execution:
![DeepinScreenshot_select-area_20210311121452](https://user-images.githubusercontent.com/4982789/110834729-859d8c00-8263-11eb-98cd-212f69111e5d.png)

**Comment by umesh-timalsina** [comment]
I know this issue. This happens when there are multiple return statements in your operation's execute method.

**Comment by brollb** [comment]
Hmm... The `ComputeFeatures` operation doesn't have multiple return statements but it seems like it might be related:
```python
from keras.models import Model

class ComputeFeatures():
    def __init__(self, model):
        self.model = model

    def execute(self, dataset, weights):
        self.model.set_weights(weights)
        X = dataset['X']
        y = dataset['y']
        feature_model = Model(inputs=self.model.inputs, outputs=self.model.layers[-2].output)
        feat = feature_model.predict(X)
        new_dataset = {'X': feat, 'y': y}
        return new_dataset
```
