### ISSUE TITLE
Walkthroughs

### ISSUE THREAD

**Issue by brollb** [deepforge-dev/deepforge#408]
We should provide some walkthroughs (screencasts, most likely) stepping through the provided demos

**Comment by kazadi** [comment]
i agree. I've followed the instructions (installed mongo, used NPM for deepforge) yet I'm still unable to get the IDE to work. Terminal doesn't appear to give any errors when `deepforge start` is entered. apologies if this isn't the proper area to post this

**Comment by brollb** [comment]
Can you upload the logs? You should be able to redirect them to a file using `deepforge start 2&> df_logs.txt`

**Comment by brollb** [comment]
Did you open a browser to `http://localhost:8888`?

**Comment by kazadi** [comment]
Yep. Getting the "This site can’t be reached" error. Hmm. the df_logs.txt file is coming up blank. I'll attach a screenshot of my terminal.
![screen shot 2016-12-08 at 3 36 01 pm](https://cloud.githubusercontent.com/assets/12902151/21028755/355c9bb2-bd5c-11e6-8be2-b15aa5e51747.png)

**Comment by brollb** [comment]
do you mind moving to the gitter? It might be easier to have this type of discussion there and then just post back the solution here. https://gitter.im/deepforge-dev/deepforge

**Comment by brollb** [comment]
This issue was caused by using an unsupported version of nodejs (v7) and was fixed by reverting to nodejs v6.

**Comment by brollb** [comment]
we could probably do something like https://deeplearning4j.org/tutorials

**Comment by brollb** [comment]
Walkthroughs have since been added to the readthedocs: http://deepforge.readthedocs.org/
