### ISSUE TITLE
Cannot merge forks of running jobs that update frequently

### ISSUE THREAD

**Issue by JimnyCricket** [deepforge-dev/deepforge#754]
When running two training tasks (2 separate architectures). The branches will not merge because the status bar is committing while the merge is attempted.

**Comment by brollb** [comment]
As of #785, the stdout should not be committed to the project so the status bar should not cause issues w/ merging

This could still be an issue if you are the branches are doing something like updating a graph (`deepforge.Graph`) every second but I suspect this scenario is much less likely.

Thoughts?
